Hi filter appointments
ProyectoIntegrador2018/salud360 pull request #130
Opened 2019-04-29 20:37 UTC by HernanIruegas

2019-04-30 00:31 UTC, jvann requested changes
@HernanIruegas  Quita los commits el schema change, eso no se hace directo y nisiquiera deberia de estar commiteado.

2019-04-30 00:31 UTC, jvann commented on db/schema.rb
> +    t.float "agua"
@VictorElizalde  Esto no esta bien o si? esto ya lo tenias tu cambiado ?
@HernanIruegas  que hace esto aqui? el schema se cambia mediante migraciones no directo, aparte de que esto ya deberia de estar cambiado, no? 🤔

2019-04-30 00:31 UTC, jvann commented on db/schema.rb
> +    t.float "cintura"
@HernanIruegas  -.-

2019-04-30 22:06 UTC, kurenn commented
@HernanIruegas te voy a pedir que seamos honestos, y que no hagamos `commits` de manera deliberada y que solamente fueron generados por incrementar la calificacion. 

Un commit por un espacio en blanco en el caso de 3d006fe o para cerrar un condicional en otro commit, como en el caso de bba6205 me habla de una falta de respeto al reglamento institucional y a tu equipo. 

Este pull request y consecuentes seran revisados por mi, en caso de que se hagan commits a master directo no los tomare en cuenta de no haber sido revisados previamente.

La dinamica sera la siguiente:

* Todos los pull request que se hagan por parte de @HernanIruegas deberan pasar por una revision mia y seran integrados en formato `squash`.

2019-04-30 23:41 UTC, HernanIruegas commented
> @HernanIruegas te voy a pedir que seamos honestos, y que no hagamos `commits` de manera deliberada y que solamente fueron generados por incrementar la calificacion.
> 
> Un commit por un espacio en blanco en el caso de [3d006fe](https://github.com/ProyectoIntegrador2018/salud360/commit/3d006fe45416d6309c6b2bd352d37fa293b0784c) o para cerrar un condicional en otro commit, como en el caso de [bba6205](https://github.com/ProyectoIntegrador2018/salud360/commit/bba62057c3b5731c85d4848fcda2ef7dcd42a753) me habla de una falta de respeto al reglamento institucional y a tu equipo.
> 
> Este pull request y consecuentes seran revisados por mi, en caso de que se hagan commits a master directo no los tomare en cuenta de no haber sido revisados previamente.
> 
> La dinamica sera la siguiente:
> 
> * Todos los pull request que se hagan por parte de @HernanIruegas deberan pasar por una revision mia y seran integrados en formato `squash`.

2019-04-30 23:48 UTC, HernanIruegas commented
> @HernanIruegas te voy a pedir que seamos honestos, y que no hagamos `commits` de manera deliberada y que solamente fueron generados por incrementar la calificacion.
> 
> Un commit por un espacio en blanco en el caso de [3d006fe](https://github.com/ProyectoIntegrador2018/salud360/commit/3d006fe45416d6309c6b2bd352d37fa293b0784c) o para cerrar un condicional en otro commit, como en el caso de [bba6205](https://github.com/ProyectoIntegrador2018/salud360/commit/bba62057c3b5731c85d4848fcda2ef7dcd42a753) me habla de una falta de respeto al reglamento institucional y a tu equipo.
> 
> Este pull request y consecuentes seran revisados por mi, en caso de que se hagan commits a master directo no los tomare en cuenta de no haber sido revisados previamente.
> 
> La dinamica sera la siguiente:
> 
> * Todos los pull request que se hagan por parte de @HernanIruegas deberan pasar por una revision mia y seran integrados en formato `squash`.

Que tal Profesor, entiendo su argumento y si hay commits que no deberían estar ahí. De ninguna manera fue mi intención ser deshonesto aunque entiendo su punto de vista de porque parece ser así, pero le explico. En el segundo parcial realice dos cards y las subí como un commit por card, lo cual afecto mi calificación. Usted menciono que podíamos explicarle por llamada lo que habíamos hecho para que la calificación no se basara en commits solamente, desafortunadamente no tuve tiempo para hacerlo porque al día siguiente me fui de viaje 11 días. Por este motivo fue que agregue commits de más en esta card, para compensar por las dos cards anteriores. No se preocupe que ya realice otro pull request en donde solo está un commit por la card que hice. De nuevo, le ofrezco una disculpa por esta situación, espero entienda mi punto de vista y podamos continuar con el merge del nuevo pull request para que el cliente no quede afectado de manera negativa.

2019-05-01 00:23 UTC, kurenn commented
@HernanIruegas Por favor corrige las observaciones de Jorge y Victor con respecto al `schema.rb` para poder darle revision

2019-05-01 03:48 UTC, jvann commented
@kurenn  Dado que @HernanIruegas creo otro PR para este desarollo cerrare este PR para que quede limpio y no haya confusiones. 

Follow-up #134

2019-05-01 03:48 UTC, closed without merging